language: php

php:
 - 7.1.3

before_script:
 - cp .env.travis .env.example
 - composer self-update
 - composer install --prefer-source --no-interaction
 - php artisan key:generate

script:
 - vendor/bin/phpunit